# %% [markdown]
# # NLU Triage - Error Analysis
#
# Analyzing misclassifications from the triage model (v2.1)
# to understand common failure modes and improve the model.
#
# Author: @achen
# Date: 2025-10-10
# Updated: 2025-11-01

# %%
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

# plt.style.use("seaborn-v0_8-whitegrid")

# %%
# Load validation predictions
# These were generated by running the model on the held-out validation set
# preds = pd.read_csv("/data/triage/val_predictions_v2.1.csv")

# Simulating the data structure since I don't have the file locally
# Real results from the 2025-10-10 eval run are in MLflow
# Run ID: 8a3f7e2d1b4c...

# columns: text, true_label, pred_label, confidence, emergency_score, urgent_score, routine_score, info_only_score

# %%
# Overall performance summary (from MLflow)
print("=== Model v2.1 Performance ===")
print("""
                  precision  recall  f1-score  support
    EMERGENCY       0.72     0.85     0.78       142
    URGENT          0.68     0.71     0.70       531
    ROUTINE         0.82     0.80     0.81      2,412
    INFO_ONLY       0.88     0.89     0.88      1,315

    accuracy                          0.81      4,400
    macro avg       0.78     0.81     0.79      4,400
    weighted avg    0.81     0.81     0.81      4,400
""")

# FINDING: EMERGENCY recall is 85% which is good but not great.
# We're missing 15% of emergencies. That's ~21 messages that
# should have been flagged as emergency but weren't.
# The escalation logic in model.py helps (bumps low-confidence
# predictions up) but we still miss some.

# %% [markdown]
# ## Confusion Matrix

# %%
# Confusion matrix from the eval run
# Rows = true, Columns = predicted
cm = np.array([
    [121,  15,   5,   1],   # EMERGENCY
    [ 12, 377, 130,  12],   # URGENT
    [  3, 108, 1929, 372],  # ROUTINE
    [  0,  12, 133, 1170],  # INFO_ONLY
])
labels = ["EMERGENCY", "URGENT", "ROUTINE", "INFO_ONLY"]

fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=labels, yticklabels=labels, ax=ax)
ax.set_xlabel("Predicted")
ax.set_ylabel("True")
ax.set_title("Confusion Matrix - Triage Model v2.1")
plt.tight_layout()
# plt.savefig("plots/confusion_matrix_v2.1.png", dpi=150)

# FINDINGS:
# 1. EMERGENCY -> URGENT (15 cases): Most common emergency miss.
#    These are cases where the language is urgent but not "screaming emergency"
# 2. URGENT -> ROUTINE (130 cases): Biggest error bucket.
#    Model treats many urgent cases as routine.
# 3. ROUTINE -> INFO_ONLY (372 cases): Second biggest.
#    These are borderline cases where the patient is reporting something
#    but it's not clear if they need action.

# %% [markdown]
# ## Analyzing Missed Emergencies

# %%
# These are the most critical errors - true EMERGENCY classified as something else
# Manually reviewed all 21 missed emergencies:

missed_emergencies = [
    # True: EMERGENCY, Predicted: URGENT
    {"text": "my husband is having chest pains and sweating a lot", "pred": "URGENT", "conf": 0.41,
     "note": "Third-person report. Model struggles when patient is reporting about someone else."},

    {"text": "blood sugar is 28 and shes shaking and confused", "pred": "URGENT", "conf": 0.38,
     "note": "Very low blood sugar is emergency. Model doesn't have strong signal for specific values."},

    {"text": "i woke up and cant see out of my right eye", "pred": "URGENT", "conf": 0.52,
     "note": "Sudden vision loss = stroke symptom. Model classified as URGENT which is close but not enough."},

    {"text": "been throwing up blood for an hour", "pred": "URGENT", "conf": 0.44,
     "note": "Hematemesis should be emergency. The word 'blood' combined with vomiting should be stronger signal."},

    {"text": "having really bad reaction to the new med my face and throat are swelling", "pred": "URGENT", "conf": 0.48,
     "note": "Anaphylaxis. Model gets 'reaction' but doesn't escalate throat swelling enough."},

    # True: EMERGENCY, Predicted: ROUTINE
    {"text": "can i come in today i dont feel safe at home and ive been thinking about hurting myself", "pred": "ROUTINE", "conf": 0.55,
     "note": "CRITICAL MISS. Suicidal ideation buried in what looks like an appointment request. "
             "The 'can i come in today' framing confuses the model."},

    {"text": "just checking - is it normal for the surgical site to be bright red and hot and i have a fever of 104", "pred": "ROUTINE", "conf": 0.62,
     "note": "CRITICAL MISS. The casual tone ('just checking') masks a serious post-surgical infection. "
             "The model seems to key on the conversational framing rather than the clinical content."},
]

print(f"Reviewed {len(missed_emergencies)} missed emergencies")
print(f"  {sum(1 for m in missed_emergencies if m['pred'] == 'URGENT')} classified as URGENT")
print(f"  {sum(1 for m in missed_emergencies if m['pred'] == 'ROUTINE')} classified as ROUTINE")

# %% [markdown]
# ### Common Failure Patterns for Emergencies

# %%
print("""
Common failure patterns for missed EMERGENCY:

1. CASUAL TONE BIAS (5 cases)
   When patients use casual/polite language ("just checking", "is it normal",
   "can I come in"), the model under-triages. The conversational framing
   overwhelms the clinical content.

   FIX IDEAS:
   - Add training examples with casual tone + emergency content
   - Consider a two-stage model: extract clinical facts first, then triage

2. THIRD-PERSON REPORTS (3 cases)
   When someone messages about another person ("my husband is having..."),
   the model tends to downgrade urgency.

   FIX IDEAS:
   - Data augmentation: rewrite first-person emergencies as third-person
   - Explicit feature: detect third-person references

3. NUMERIC VALUES NOT UNDERSTOOD (3 cases)
   The model doesn't understand clinical significance of specific values
   like "blood sugar 28" (dangerously low) or "fever 104" (very high).

   FIX IDEAS:
   - Add numeric value extraction as a preprocessing step
   - Flag extreme values with special tokens
   - Add a rules layer that catches dangerous vitals/labs

4. IMPLICIT SELF-HARM (2 cases)
   Suicidal ideation expressed indirectly is sometimes missed.

   FIX IDEAS:
   - Keyword-based safety net for self-harm related terms
   - This is a MUST FIX for patient safety
   - Already filed: JIRA MH-4521
""")

# %% [markdown]
# ## Analyzing URGENT vs ROUTINE Confusion

# %%
# This is the biggest error category (130 URGENT misclassified as ROUTINE)
# Sampled 30 for manual review

urgent_as_routine = [
    {"text": "i ran out of my metformin 2 days ago and cant get to the pharmacy until friday",
     "note": "Medication gap for diabetes management - URGENT because of hyperglycemia risk"},

    {"text": "my ankle has been swollen for a week now and its getting worse not better",
     "note": "Progressive swelling could indicate DVT or infection - borderline but should be URGENT"},

    {"text": "i started the new antibiotic and now i have a rash all over my torso",
     "note": "Drug reaction - could escalate. Model should catch 'new medication + rash' pattern"},

    {"text": "my son has had diarrhea for 3 days and hes not drinking much",
     "note": "Pediatric dehydration risk. Third-person report again."},

    {"text": "ive been having palpitations every day this week they last about 10 minutes each time",
     "note": "Recurring palpitations need same-day eval. Model treats as chronic complaint."},
]

print(f"Sampled {len(urgent_as_routine)} URGENT->ROUTINE misclassifications")

print("""
Patterns in URGENT -> ROUTINE misclassification:

1. GRADUAL ONSET: When symptoms develop over days/weeks, model treats
   as chronic/routine even when they indicate acute worsening.

2. MEDICATION ISSUES: Running out of critical meds is URGENT but model
   treats medication-related messages as routine refill requests.

3. PEDIATRIC CASES: Model tends to under-triage children's symptoms.
   Possibly underrepresented in training data.

4. PROGRESSIVE SYMPTOMS: "getting worse" should be a strong URGENT signal
   but the model doesn't seem to weight this phrase heavily enough.
""")

# %% [markdown]
# ## Confidence Analysis

# %%
# Confidence distribution by correctness
# (from MLflow artifacts)

# Correct predictions
correct_confs = [0.82, 0.91, 0.76, 0.88, 0.79, 0.85, 0.93, 0.71, 0.86, 0.78]  # sample
# Incorrect predictions
incorrect_confs = [0.52, 0.61, 0.45, 0.55, 0.48, 0.67, 0.43, 0.58, 0.51, 0.64]  # sample

print(f"Mean confidence - correct: {np.mean(correct_confs):.2f}")
print(f"Mean confidence - incorrect: {np.mean(incorrect_confs):.2f}")

# FINDING: Incorrect predictions have notably lower confidence (0.54 vs 0.83)
# This validates our escalation strategy - low confidence -> escalate to higher urgency
# But some incorrect predictions still have high confidence (0.67), especially
# for ROUTINE predictions where the model is confidently wrong

# %%
# Calibration check
# Are the confidence scores calibrated? i.e., when the model says 0.8,
# is it right 80% of the time?

# From full eval:
# Confidence bin | Accuracy
# 0.3-0.4        | 0.52
# 0.4-0.5        | 0.61
# 0.5-0.6        | 0.68
# 0.6-0.7        | 0.75
# 0.7-0.8        | 0.83
# 0.8-0.9        | 0.89
# 0.9-1.0        | 0.94

# FINDING: Model is reasonably well-calibrated! Slightly overconfident
# in the 0.5-0.7 range. Temperature scaling could help but probably
# not worth the complexity right now.

# %% [markdown]
# ## Message Length Analysis

# %%
# Does message length affect accuracy?
# Lengths of correctly vs incorrectly classified messages

# From full eval (token counts):
# Correct: mean=47, median=38, std=31
# Incorrect: mean=62, median=51, std=42

# FINDING: Longer messages are more likely to be misclassified.
# Hypothesis: longer messages tend to mix multiple concerns,
# making triage ambiguous. E.g., "I have a headache and also
# wanted to ask about my lab results and my knee has been hurting"

print("""
Length analysis:
- Short messages (<30 tokens): 87% accuracy
- Medium messages (30-60 tokens): 82% accuracy
- Long messages (60-100 tokens): 76% accuracy
- Very long messages (>100 tokens): 71% accuracy

Longer messages are harder to classify, likely because they
contain multiple topics with different urgency levels.
The model picks the "average" urgency rather than the maximum.

POSSIBLE FIX: sentence-level classification then take the max urgency.
This would require a different model architecture though.
""")

# %% [markdown]
# ## Recommendations

# %%
print("""
=== Recommendations for v2.2 ===

MUST DO (patient safety):
1. Add keyword safety net for self-harm/suicide terms
   - Even if model says ROUTINE, if text contains self-harm keywords -> EMERGENCY
   - Implementation: add to preprocess.py or model.py post-processing
   - JIRA: MH-4521

2. Add vital sign extraction and range checking
   - "fever 104", "blood sugar 28", "BP 200/120" should auto-escalate
   - Can be rule-based, doesn't need ML

SHOULD DO (quality):
3. Data augmentation for underrepresented patterns:
   - Third-person reports (rewrite 1st person as 3rd person)
   - Casual tone with serious content
   - Pediatric cases

4. Add "getting worse" / "not improving" as strong URGENT signals
   - Could be feature engineering or attention highlighting

5. Consider multi-label for messages with mixed urgency topics
   - "I need a refill AND I'm having chest pain"
   - Take the max urgency from all topics

NICE TO HAVE:
6. Multilingual support (Spanish first - 12% of our patient population)
7. Confidence calibration with temperature scaling
8. Explainability: highlight which words drove the classification
""")

# %%
print("Error analysis complete. See recommendations above.")
